# Generated by Django 4.1.3 on 2022-11-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
