# Generated by Django 4.1.3 on 2022-11-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0003_products_chain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='chain_name',
            new_name='chain',
        ),
    ]
