# Generated by Django 4.1.3 on 2023-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0008_products_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reselled',
            field=models.BooleanField(default=True),
        ),
    ]
