# Generated by Django 4.1.3 on 2023-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0012_alter_products_reselled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='new_owner',
            field=models.CharField(default='afrinjasim', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='old_owner',
            field=models.CharField(default='afrinjasim', max_length=100, null=True),
        ),
    ]
