# Generated by Django 4.1.3 on 2023-01-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_wallet_amount_wallet_wall_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wall_amount',
            field=models.FloatField(blank=True, default=250, null=True),
        ),
    ]
