# Generated by Django 4.1.3 on 2022-12-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_quantity_guestcart_quantity_oldcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
