# Generated by Django 4.1.3 on 2022-12-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='balance',
        ),
    ]
