# Generated by Django 4.1.3 on 2022-12-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_remove_oldcart_purchase_delete_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
