# Generated by Django 4.1.3 on 2022-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_oldcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(default='paypal', max_length=100),
        ),
    ]
