# Generated by Django 4.1.3 on 2023-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
