# Generated by Django 4.1.3 on 2023-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_order_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='soldout',
            field=models.BooleanField(default=False),
        ),
    ]
